export default {
  net: {
    GET_CATEGORIES: 'GET_CATEGORIES',
    GET_PRODUCTS: 'GET_PRODUCTS',

    SET_CATEGORIES_TO_STORE: 'SET_CATEGORIES_TO_STORE',
    SET_PRODUCTS_TO_STORE: 'SET_PRODUCTS_TO_STORE',

    ADD_CATEGORY: 'ADD_CATEGORY',
    ADD_PRODUCT: 'ADD_PRODUCT',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',

    DELETE_A_RECORD: 'DELETE_A_RECORD',
  },
}
